// <auto-generated/>
//
// AsyncRpcSourceGenerator
// ------------------------
// A Roslyn IIncrementalGenerator (compatible with Microsoft.CodeAnalysis.CSharp 4.3.0)
// that turns a single hand-written "source of truth" method:
//
//     [AsyncRpc]
//     private async UniTask<AsyncRpcResult> FooServerAsync(int a, ulong b) { /* logic */ }
//
// into the two wrapper members described by the template:
//
//     public UniTask<AsyncRpcResult> InvokeFooAction(int a, ulong b, CancellationToken token)
//     {
//         return rpcManager.PerformAsyncRpcAction(FooAction, token);
//         void FooAction(AsyncRpcToken actionToken) => FooAction_ServerRpc(actionToken, a, b);
//     }
//
//     [Rpc(SendTo.Server)]
//     private void FooAction_ServerRpc(AsyncRpcToken asyncToken, int a, ulong b)
//     {
//         var task = FooServerAsync(a, b);
//         rpcManager.PerformServerRpcAction(asyncToken, task).Forget();
//     }
//
// Requirements / assumptions (matching the template):
//   * The containing type must be declared `partial` (a diagnostic is reported otherwise).
//   * A `rpcManager` member with PerformAsyncRpcAction / PerformServerRpcAction must be in scope.
//   * AsyncRpcToken / AsyncRpcResult / Rpc / SendTo / UniTask.Forget resolve via the `using`
//     directives copied from the source file. CancellationToken is fully qualified, so no extra
//     using is required for it.
//   * [FUNC] is the source method name with the trailing "ServerAsync" removed.
//
// The [AsyncRpc] marker attribute (AsyncRpcGen.AsyncRpcAttribute) is emitted by this generator,
// so add `using AsyncRpcGen;` (or use [AsyncRpcGen.AsyncRpc]) on your methods.

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace AsyncRpcGen
{
    [Generator]
    public sealed class AsyncRpcSourceGenerator : IIncrementalGenerator
    {
        private const string AttributeNamespace = "AsyncRpcGen";
        private const string AttributeMetadataName = AttributeNamespace + ".AsyncRpcAttribute";
        private const string RpcManagerAttributeMetadataName = AttributeNamespace + ".RpcManagerAttribute";
        private const string ServerAsyncSuffix = "ServerAsync";
        private const string AsyncSuffix = "Async";

        private const string RpcManagerAttributeSource =
@"// <auto-generated/>
namespace " + AttributeNamespace + @"
{
    /// <summary>
    /// Marks a field or property as the <c>AsyncRpcManager</c> instance to use in generated RPC
    /// wrappers. When present the generator uses the decorated member's name instead of the
    /// default <c>rpcManager</c>.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Field | global::System.AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
    internal sealed class RpcManagerAttribute : global::System.Attribute
    {
    }
}
";

        private const string AttributeSource =
@"// <auto-generated/>
namespace " + AttributeNamespace + @"
{
    /// <summary>
    /// Mark a private <c>UniTask&lt;AsyncRpcResult&gt;</c> method as the source of truth for an
    /// async RPC. The AsyncRpcSourceGenerator emits the matching Invoke*Action wrapper and the
    /// [Rpc(SendTo.Server)] *_ServerRpc method into a partial copy of the containing type.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
    internal sealed class AsyncRpcAttribute : global::System.Attribute
    {
    }
}
";

        private static readonly DiagnosticDescriptor NotPartial = new DiagnosticDescriptor(
            id: "ASYNCRPC001",
            title: "[AsyncRpc] method must live in a partial type",
            messageFormat: "Type '{0}' contains an [AsyncRpc] method but is not declared 'partial'; the generated RPC wrappers cannot be emitted",
            category: "AsyncRpcGen",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        private static readonly DiagnosticDescriptor NoRpcManager = new DiagnosticDescriptor(
            id: "ASYNCRPC003",
            title: "[AsyncRpc] method's type has no [RpcManager] member",
            messageFormat: "Type '{0}' contains an [AsyncRpc] method but no field or property is marked [RpcManager]; the generated RPC wrappers cannot be emitted",
            category: "AsyncRpcGen",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        private static readonly DiagnosticDescriptor BadSuffix = new DiagnosticDescriptor(
            id: "ASYNCRPC002",
            title: "[AsyncRpc] method name should end with 'ServerAsync'",
            messageFormat: "Method '{0}' is marked [AsyncRpc] but does not end with 'ServerAsync'; the generated names are derived from the verbatim method name instead",
            category: "AsyncRpcGen",
            defaultSeverity: DiagnosticSeverity.Warning,
            isEnabledByDefault: true);

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // Emit the marker attribute so [AsyncRpc] exists and is visible to
            // ForAttributeWithMetadataName in the same compilation pass.
            context.RegisterPostInitializationOutput(ctx =>
            {
                ctx.AddSource("AsyncRpcAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8));
                ctx.AddSource("RpcManagerAttribute.g.cs", SourceText.From(RpcManagerAttributeSource, Encoding.UTF8));
            });

            IncrementalValuesProvider<AsyncRpcMethod> methods = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    AttributeMetadataName,
                    predicate: (node, _) => node is MethodDeclarationSyntax,
                    transform: (ctx, _) => GetMethodModel(ctx))
                .Where(m => m != null);

            context.RegisterSourceOutput(methods.Collect(), Emit);
        }

        private static AsyncRpcMethod GetMethodModel(GeneratorAttributeSyntaxContext ctx)
        {
            var methodSymbol = ctx.TargetSymbol as IMethodSymbol;
            if (methodSymbol == null)
            {
                return null;
            }

            var node = (MethodDeclarationSyntax)ctx.TargetNode;

            // Walk up the syntax tree to collect the chain of containing type declarations
            // (outer-to-inner) so we can re-open them as partial types in the generated file.
            var typeChain = new List<TypeShell>();
            bool allPartial = true;
            for (SyntaxNode parent = node.Parent; parent != null; parent = parent.Parent)
            {
                var typeDecl = parent as TypeDeclarationSyntax;
                if (typeDecl == null)
                {
                    continue;
                }

                bool isPartial = typeDecl.Modifiers.Any(t => t.IsKind(SyntaxKind.PartialKeyword));
                allPartial = allPartial && isPartial;

                string typeParams = typeDecl.TypeParameterList != null
                    ? typeDecl.TypeParameterList.ToString()
                    : string.Empty;

                typeChain.Add(new TypeShell(
                    keyword: typeDecl.Keyword.ValueText,
                    name: typeDecl.Identifier.ValueText,
                    typeParameters: typeParams,
                    isPartial: isPartial));
            }
            typeChain.Reverse();

            // Copy every using directive from the source file so framework types
            // (UniTask, Rpc, SendTo, AsyncRpcToken, AsyncRpcResult, Forget, ...) resolve.
            var usings = new List<string>();
            foreach (var u in node.SyntaxTree.GetRoot().DescendantNodes().OfType<UsingDirectiveSyntax>())
            {
                usings.Add(u.ToString().Trim());
            }

            // Parameters from the symbol, fully qualified so they resolve regardless of usings.
            var parameters = new List<ParamInfo>();
            foreach (var p in methodSymbol.Parameters)
            {
                parameters.Add(new ParamInfo(
                    type: p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    name: p.Name,
                    refKind: p.RefKind));
            }

            var rpcManagerMember = methodSymbol.ContainingType.GetMembers()
                .FirstOrDefault(member => member.GetAttributes()
                    .Any(a => a.AttributeClass?.ToDisplayString() == RpcManagerAttributeMetadataName));
            string rpcManagerName = rpcManagerMember?.Name;

            string sourceName = methodSymbol.Name;
            string funcName;
            bool badSuffix = false;
            if (sourceName.EndsWith(ServerAsyncSuffix, System.StringComparison.Ordinal) &&
                sourceName.Length > ServerAsyncSuffix.Length)
            {
                funcName = sourceName.Substring(0, sourceName.Length - ServerAsyncSuffix.Length);
            }
            else if (sourceName.EndsWith(AsyncSuffix, System.StringComparison.Ordinal) &&
                     sourceName.Length > AsyncSuffix.Length)
            {
                funcName = sourceName.Substring(0, sourceName.Length - AsyncSuffix.Length);
                badSuffix = true;
            }
            else
            {
                funcName = sourceName;
                badSuffix = true;
            }

            INamespaceSymbol ns = methodSymbol.ContainingType.ContainingNamespace;
            string namespaceName = (ns == null || ns.IsGlobalNamespace)
                ? string.Empty
                : ns.ToDisplayString();

            return new AsyncRpcMethod(
                namespaceName: namespaceName,
                typeChain: typeChain,
                funcName: funcName,
                sourceMethodName: sourceName,
                returnType: methodSymbol.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                parameters: parameters,
                usings: usings,
                allTypesPartial: allPartial,
                badSuffix: badSuffix,
                rpcManagerName: rpcManagerName,
                location: node.Identifier.GetLocation());
        }

        private static void Emit(SourceProductionContext spc, ImmutableArray<AsyncRpcMethod> models)
        {
            if (models.IsDefaultOrEmpty)
            {
                return;
            }

            // Report diagnostics first.
            foreach (var m in models)
            {
                if (!m.AllTypesPartial)
                {
                    string typeName = m.TypeChain.Count > 0
                        ? m.TypeChain[m.TypeChain.Count - 1].Name
                        : "<global>";
                    spc.ReportDiagnostic(Diagnostic.Create(NotPartial, m.Location, typeName));
                }

                if (m.BadSuffix)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(BadSuffix, m.Location, m.SourceMethodName));
                }

                if (m.RpcManagerName == null)
                {
                    string typeName = m.TypeChain.Count > 0
                        ? m.TypeChain[m.TypeChain.Count - 1].Name
                        : "<global>";
                    spc.ReportDiagnostic(Diagnostic.Create(NoRpcManager, m.Location, typeName));
                }
            }

            // Group methods by the type they live in so one file is emitted per type.
            var groups = new Dictionary<string, List<AsyncRpcMethod>>();
            foreach (var m in models)
            {
                if (!m.AllTypesPartial || m.RpcManagerName == null)
                {
                    continue; // diagnostic already reported; cannot emit
                }

                string key = GroupKey(m);
                List<AsyncRpcMethod> list;
                if (!groups.TryGetValue(key, out list))
                {
                    list = new List<AsyncRpcMethod>();
                    groups[key] = list;
                }
                list.Add(m);
            }

            foreach (var pair in groups)
            {
                var methodsInType = pair.Value;
                string source = BuildTypeSource(methodsInType);
                string hint = SanitizeHint(pair.Key) + ".AsyncRpc.g.cs";
                spc.AddSource(hint, SourceText.From(source, Encoding.UTF8));
            }
        }

        private static string GroupKey(AsyncRpcMethod m)
        {
            var sb = new StringBuilder();
            sb.Append(m.NamespaceName);
            sb.Append("::");
            foreach (var t in m.TypeChain)
            {
                sb.Append(t.Name);
                sb.Append(t.TypeParameters);
                sb.Append('.');
            }
            return sb.ToString();
        }

        private static string SanitizeHint(string raw)
        {
            var sb = new StringBuilder(raw.Length);
            foreach (char c in raw)
            {
                sb.Append(char.IsLetterOrDigit(c) ? c : '_');
            }
            return sb.ToString();
        }

        private static string BuildTypeSource(List<AsyncRpcMethod> methodsInType)
        {
            var first = methodsInType[0];

            // Union of all using directives across the methods in this type.
            var usingSet = new List<string>();
            var seen = new HashSet<string>();
            foreach (var m in methodsInType)
            {
                foreach (var u in m.Usings)
                {
                    if (seen.Add(u))
                    {
                        usingSet.Add(u);
                    }
                }
            }

            const string netcodeUsing = "using Unity.Netcode;";
            if (seen.Add(netcodeUsing))
            {
                usingSet.Add(netcodeUsing);
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            foreach (var u in usingSet)
            {
                sb.AppendLine(u);
            }
            sb.AppendLine();

            int indent = 0;
            bool hasNamespace = !string.IsNullOrEmpty(first.NamespaceName);
            if (hasNamespace)
            {
                sb.Append(Indent(indent)).Append("namespace ").AppendLine(first.NamespaceName);
                sb.Append(Indent(indent)).AppendLine("{");
                indent++;
            }

            foreach (var t in first.TypeChain)
            {
                sb.Append(Indent(indent))
                  .Append("partial ")
                  .Append(t.Keyword)
                  .Append(' ')
                  .Append(t.Name)
                  .AppendLine(t.TypeParameters);
                sb.Append(Indent(indent)).AppendLine("{");
                indent++;
            }

            for (int i = 0; i < methodsInType.Count; i++)
            {
                if (i > 0)
                {
                    sb.AppendLine();
                }
                AppendMethods(sb, methodsInType[i], indent);
            }

            for (int i = 0; i < first.TypeChain.Count; i++)
            {
                indent--;
                sb.Append(Indent(indent)).AppendLine("}");
            }

            if (hasNamespace)
            {
                indent--;
                sb.Append(Indent(indent)).AppendLine("}");
            }

            return sb.ToString();
        }

        private static void AppendMethods(StringBuilder sb, AsyncRpcMethod m, int indent)
        {
            string ind = Indent(indent);
            string ind1 = Indent(indent + 1);
            string ind2 = Indent(indent + 2);

            string declParams = BuildDeclParams(m);
            string args = BuildArgs(m);
            bool hasParams = m.Parameters.Count > 0;

            string declWithComma = hasParams ? declParams + ", " : string.Empty;
            string argsLeadingComma = hasParams ? ", " + args : string.Empty;
            string declLeadingComma = hasParams ? ", " + declParams : string.Empty;

            string func = m.FuncName;

            // public UniTask<AsyncRpcResult> InvokeFooAction(<params>, CancellationToken token)
            sb.Append(ind).Append("public ").Append(m.ReturnType)
              .Append(" Invoke").Append(func).Append("Action(")
              .Append(declWithComma)
              .AppendLine("global::System.Threading.CancellationToken token)");
            sb.Append(ind).AppendLine("{");
            sb.Append(ind1).Append("return ").Append(m.RpcManagerName).Append(".PerformAsyncRpcAction(")
              .Append(func).AppendLine("Action, token);");
            sb.AppendLine();
            sb.Append(ind1).Append("void ").Append(func).AppendLine("Action(AsyncRpcToken actionToken)");
            sb.Append(ind1).AppendLine("{");
            sb.Append(ind2).Append(func).Append("Action_ServerRpc(actionToken")
              .Append(argsLeadingComma).AppendLine(");");
            sb.Append(ind1).AppendLine("}");
            sb.Append(ind).AppendLine("}");
            sb.AppendLine();

            // [Rpc(SendTo.Server)] private void FooAction_ServerRpc(AsyncRpcToken asyncToken, <params>)
            sb.Append(ind).AppendLine("[Rpc(SendTo.Server)]");
            sb.Append(ind).Append("private void ").Append(func)
              .Append("Action_ServerRpc(AsyncRpcToken asyncToken")
              .Append(declLeadingComma).AppendLine(")");
            sb.Append(ind).AppendLine("{");
            sb.Append(ind1).Append("var task = ").Append(m.SourceMethodName)
              .Append('(').Append(args).AppendLine(");");
            sb.Append(ind1).Append(m.RpcManagerName).AppendLine(".PerformServerRpcAction(asyncToken, task).Forget();");
            sb.Append(ind).AppendLine("}");
        }

        private static string BuildDeclParams(AsyncRpcMethod m)
        {
            var sb = new StringBuilder();
            for (int i = 0; i < m.Parameters.Count; i++)
            {
                if (i > 0)
                {
                    sb.Append(", ");
                }
                var p = m.Parameters[i];
                sb.Append(p.DeclPrefix).Append(p.Type).Append(' ').Append(p.Name);
            }
            return sb.ToString();
        }

        private static string BuildArgs(AsyncRpcMethod m)
        {
            var sb = new StringBuilder();
            for (int i = 0; i < m.Parameters.Count; i++)
            {
                if (i > 0)
                {
                    sb.Append(", ");
                }
                var p = m.Parameters[i];
                sb.Append(p.ArgPrefix).Append(p.Name);
            }
            return sb.ToString();
        }

        private static string Indent(int level)
        {
            return new string(' ', level * 4);
        }

        private sealed class AsyncRpcMethod
        {
            public AsyncRpcMethod(
                string namespaceName,
                List<TypeShell> typeChain,
                string funcName,
                string sourceMethodName,
                string returnType,
                List<ParamInfo> parameters,
                List<string> usings,
                bool allTypesPartial,
                bool badSuffix,
                string rpcManagerName,
                Location location)
            {
                NamespaceName = namespaceName;
                TypeChain = typeChain;
                FuncName = funcName;
                SourceMethodName = sourceMethodName;
                ReturnType = returnType;
                Parameters = parameters;
                Usings = usings;
                AllTypesPartial = allTypesPartial;
                BadSuffix = badSuffix;
                RpcManagerName = rpcManagerName;
                Location = location;
            }

            public string NamespaceName { get; }
            public List<TypeShell> TypeChain { get; }
            public string FuncName { get; }
            public string SourceMethodName { get; }
            public string ReturnType { get; }
            public List<ParamInfo> Parameters { get; }
            public List<string> Usings { get; }
            public bool AllTypesPartial { get; }
            public bool BadSuffix { get; }
            public string RpcManagerName { get; }
            public Location Location { get; }
        }

        private sealed class TypeShell
        {
            public TypeShell(string keyword, string name, string typeParameters, bool isPartial)
            {
                Keyword = keyword;
                Name = name;
                TypeParameters = typeParameters;
                IsPartial = isPartial;
            }

            public string Keyword { get; }
            public string Name { get; }
            public string TypeParameters { get; }
            public bool IsPartial { get; }
        }

        private sealed class ParamInfo
        {
            public ParamInfo(string type, string name, RefKind refKind)
            {
                Type = type;
                Name = name;

                switch (refKind)
                {
                    case RefKind.Ref:
                        DeclPrefix = "ref ";
                        ArgPrefix = "ref ";
                        break;
                    case RefKind.Out:
                        DeclPrefix = "out ";
                        ArgPrefix = "out ";
                        break;
                    case RefKind.In:
                        DeclPrefix = "in ";
                        ArgPrefix = string.Empty;
                        break;
                    default:
                        DeclPrefix = string.Empty;
                        ArgPrefix = string.Empty;
                        break;
                }
            }

            public string Type { get; }
            public string Name { get; }
            public string DeclPrefix { get; }
            public string ArgPrefix { get; }
        }
    }
}
